name: Auto Merge Jordan to Dev

on:
  push:
    branches:
      - jordan

jobs:
  auto-merge:
    name: Auto Merge Jordan to Dev
    runs-on: ubuntu-latest

    steps:
      # Vérifiez le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupère toutes les branches et l'historique complet

      # Configurez Git pour effectuer le merge
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Récupérez toutes les branches pour garantir la présence de `dev` et `jordan`
      - name: Fetch all branches
        run: |
          git fetch origin

      # Vérifiez si le merge est possible sans conflit
      - name: Check mergeability
        run: |
          git checkout dev
          if git merge --no-commit --no-ff origin/jordan; then
            echo "Able to merge."
            git merge --abort  # Annule l'état de merge après vérification
          else
            echo "Merge conflict detected!"
            exit 1
          fi

      # Si aucun conflit, effectuez le merge
      - name: Merge Jordan to Dev
        run: |
          git merge origin/jordan --no-ff -m "Automated merge from jordan to dev"

      # Poussez les changements sur `dev`
      - name: Push changes
        run: |
          git push origin dev