export class PurchaseCommitment {
  GenerateSettlement: boolean = false;
  CurrencyAmount!: number;
  CurrencyBalanceDue!: number;
  LiquidationType!: number;
  IsCorrected: boolean = false;
  Id!: string;
  DueDate!: Date;
  Amount!: number;
  BalanceDue!: number;
  IsDeposit: boolean = false;
  DaysNumber!: number;
  CommitmentType!: number;
  AccountingMonth: boolean = false;
  IsLiquidated: boolean = false;
  AccountingTransferState!: number;
  LiquidationAmount!: number;
  TransferedLiquidationAmount!: number;
  DocumentType!: number;
  LiquidationAccountingTransferState!: number;
  LiquidationAccountingExchangeGroupId!: string;
  ExternalDocumentId!: string;
  DocumentSubType!: number;
  LiquidationStateChangeDate!: Date;
  TransferedLiquidationStateChangeDate!: Date;
  AccountingExchangeGroupId!: string;
  ThirdId!: string;
  PaymentTypeId!: string;
  DayOfMonth!: number;
  PercentageDistribution!: number;
  DocumentId!: string;
  sysCreatedDate!: Date;
  sysCreatedUser!: string;
  sysModifiedDate!: Date;
  sysModifiedUser!: string;
  sysModuleId!: string;
  sysDatabaseId!: string;
  PreviousLiquidationType!: number;
  LiquidationCurrencyAmount!: number;
  TransferedLiquidationCurrencyAmount!: number;
  CurrencyId!: string;
  PaymentThirdId!: string;
  WithoutSettlementGapAccountingEntry: boolean = false;
}
