import { SaleDocumentLine } from "./SaleDocumentLine.type";

export class SaleDocument {
    id?: number ;
    Id: string = "";
    DocumentNumber: string = "";
    NumberPrefix: string = "";
    NumberSuffix: string = "";
    DocumentDate: string = "";
    xx_Soldee: boolean = false;
    xx_Fin_Loc: boolean = false;
    DeliveryAddress_Npai: boolean = false;
    UseInvoicingAddressAsDeliveryAddress: boolean = false;
    UseInvoicingContactAsDeliveryContact: boolean = false;
    ShippingAmountVatExcluded!: number;
    AmountVatExcludedWithDiscountAndShipping!: number;
    AmountVatExcludedWithDiscountAndShippingWithoutEcotax!: number;
    VatAmountWithoutEcotax!: number;
    VatAmount!: number;
    AmountVatIncluded!: number;
    PreviousDepositAmount!: number;
    DepositAmount!: number;
    DepositCurrencyAmount!: number;
    PreviousDepositCurrencyAmount!: number;
    TotalDueAmount!: number;
    IsEcotaxAmountIncludedToDueAmount: boolean = false;
    EcotaxAmountVatExcluded!: number;
    EcotaxVatAmount!: number;
    EcotaxAmountVatIncluded!: number;
    DetailVatAmount0_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount0_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount0_TaxAmount!: number;
    DetailVatAmount0_TaxVatAmount!: number;
    DetailVatAmount0_REAmount!: number;
    DetailVatAmount1_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount1_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount1_TaxAmount!: number;
    DetailVatAmount1_TaxVatAmount!: number;
    DetailVatAmount1_REAmount!: number;
    DetailVatAmount2_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount2_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount2_TaxAmount!: number;
    xx_Cloture: boolean = false;
    CountermarForcedkOnLines: boolean = false;
    DetailVatAmount2_TaxVatAmount!: number;
    DetailVatAmount2_REAmount!: number;
    DetailVatAmount3_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount3_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount3_TaxAmount!: number;
    DetailVatAmount3_TaxVatAmount!: number;
    DetailVatAmount3_REAmount!: number;
    DetailVatAmount4_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount4_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount4_TaxAmount!: number;
    DetailVatAmount4_TaxVatAmount!: number;
    DetailVatAmount4_REAmount!: number;
    DetailVatAmount5_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount5_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount5_TaxAmount!: number;
    DetailVatAmount5_TaxVatAmount!: number;
    DetailVatAmount5_REAmount!: number;
    VatMode!: number;
    NumberOfPackage!: number;
    IsCustomNumberOfPackage: boolean = false;
    OtherTaxAmount!: number;
    FinancialDiscountType!: number;
    FinancialDiscountRate!: number;
    FinancialDiscountAmount!: number;
    AmountWithFinancialDiscount!: number;
    NumberOfCopies!: number;
    CommitmentsBalanceDue!: number;
    AmountVatExcluded!: number;
    CostPrice!: number;
    DiscountRate!: number;
    DiscountAmount!: number;
    AmountVatExcludedWithDiscount!: number;
    DetailTaxAmount0_BaseAmount!: number;
    DetailTaxAmount0_TaxAmount!: number;
    DetailTaxAmount1_BaseAmount!: number;
    DetailTaxAmount1_TaxAmount!: number;
    DetailTaxAmount2_BaseAmount!: number;
    DetailTaxAmount2_TaxAmount!: number;
    CurrencyConversionRate!: number;
    CurrencyTotalDueAmount!: number;
    CommitmentsCurrencyBalanceDue!: number;
    CurrencyAmountVatIncluded!: number;
    CurrencyApplicationType!: number;
    CurrencyAmountVatExcluded!: number;
    CurrencyAmountVatExcludedWithDiscountAndShipping!: number;
    CurrencyAmountWithFinancialDiscount!: number;
    CurrencyShippingAmountVatExcluded!: number;
    CurrencyAmountVatExcludedWithDiscount!: number;
    CurrencyAmountVatExcludedWithDiscountAndShippingWithoutEcotax!: number;
    CurrencyEcotaxAmountVatIncluded!: number;
    CurrencyFinancialDiscountAmount!: number;
    CurrencyVatAmountWithoutEcotax!: number;
    CurrencyEcotaxVatAmount!: number;
    CurrencyEcotaxAmountVatExcluded!: number;
    CurrencyVatAmount!: number;
    CurrencyDiscountAmount!: number;
    DocumentType!: number;
    InterestAmountVatExcluded!: number;
    InterestRate!: number;
    HumanServiceTotalAmount!: number;
    HumanServiceAmountSettledByOther!: number;
    HumanServiceAmountSettledByCESU!: number;
    HumanServiceAmountSettledByCESUP!: number;
    HumanServiceDeductibleAmount!: number;
    GrossInterestBase!: number;
    GrossInterestRate!: number;
    GrossInterestAmount!: number;
    Printed: boolean = false;
    SubjectToRE: boolean = false;
    REAmount!: number;
    TotalNetWeight!: number;
    CorrectionType!: number;
    IRPFAmount!: number;
    IRPFRate!: number;
    PriceWithTaxBased: boolean = false;
    CustomerId!: string;
    CustomerName!: string;
    Revision!: string;
    xx_Location: boolean = false;
    xx_Nouveau_Client: boolean = false;
    xx_Separ1: boolean = false;
    xx_Separ2: boolean = false;
  
    //* --------------------------------- Les champs avec des IDs
    ShippingVatId!: string;
    ReportId!: string;
    TerritorialityId!: string;
    VatId!: string;
    InvoicingChargesVatId!: string;
    InvoicingAddressId!: string;
    InvoicingContactId!: string;
    DeliveryAddressId!: string;
    DeliveryContactId!: string;
    AssociatedInvoiceId!: string;
    AssociatedDeliveryOrderId!: string;
    AssociatedOrderId!: string;
    StorehouseId!: string;
    TransferedDocumentId!: string;
    sysModuleId!: string;
    sysDatabaseId!: string;
    sysRecordVersionId!: string;
    ThirdBankAccountId!: string;
    DetailTaxAmount0_VatId!: string;
    DetailTaxAmount1_VatId!: string;
    DetailTaxAmount2_VatId!: string;
    DetailTaxAmount3_VatId!: string;
    DetailTaxAmount4_VatId!: string;
    DetailTaxAmount5_VatId!: string;
    CustomerHeadOfficeAddressId!: string;
    AppliedPriceListLineId!: string;
    Hash_Hash_ChainedId!: string;
    DocumentOptionsId!: string;
  }
  

  export class SaleDocumentWithLines {
    SaleDocumentLine: SaleDocumentLine[] = [];
    //---------------------------------------------
    Id: string = "";
    DocumentNumber: string = "";
    NotesClear: string = "";
    xx_Soldee: boolean = false;
    xx_Fin_Loc: boolean = false;
    DeliveryAddress_Npai: boolean = false;
    UseInvoicingAddressAsDeliveryAddress: boolean = false;
    UseInvoicingContactAsDeliveryContact: boolean = false;
    ShippingAmountVatExcluded!: number;
    AmountVatExcludedWithDiscountAndShipping!: number;
    AmountVatExcludedWithDiscountAndShippingWithoutEcotax!: number;
    VatAmountWithoutEcotax!: number;
    VatAmount!: number;
    AmountVatIncluded!: number;
    PreviousDepositAmount!: number;
    DepositAmount!: number;
    DepositCurrencyAmount!: number;
    PreviousDepositCurrencyAmount!: number;
    TotalDueAmount!: number;
    IsEcotaxAmountIncludedToDueAmount: boolean = false;
    EcotaxAmountVatExcluded!: number;
    EcotaxVatAmount!: number;
    EcotaxAmountVatIncluded!: number;
    DetailVatAmount0_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount0_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount0_TaxAmount!: number;
    DetailVatAmount0_TaxVatAmount!: number;
    DetailVatAmount0_REAmount!: number;
    DetailVatAmount1_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount1_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount1_TaxAmount!: number;
    DetailVatAmount1_TaxVatAmount!: number;
    DetailVatAmount1_REAmount!: number;
    DetailVatAmount2_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount2_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount2_TaxAmount!: number;
    xx_Cloture: boolean = false;
    CountermarForcedkOnLines: boolean = false;
    DetailVatAmount2_TaxVatAmount!: number;
    DetailVatAmount2_REAmount!: number;
    DetailVatAmount3_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount3_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount3_TaxAmount!: number;
    DetailVatAmount3_TaxVatAmount!: number;
    DetailVatAmount3_REAmount!: number;
    DetailVatAmount4_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount4_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount4_TaxAmount!: number;
    DetailVatAmount4_TaxVatAmount!: number;
    DetailVatAmount4_REAmount!: number;
    DetailVatAmount5_VatAmountOnCollectionWithoutDeposit!: number;
    DetailVatAmount5_VatAmountOnDebitWithoutDeposit!: number;
    DetailVatAmount5_TaxAmount!: number;
    DetailVatAmount5_TaxVatAmount!: number;
    DetailVatAmount5_REAmount!: number;
    VatMode!: number;
    NumberOfPackage!: number;
    IsCustomNumberOfPackage: boolean = false;
    OtherTaxAmount!: number;
    FinancialDiscountType!: number;
    FinancialDiscountRate!: number;
    FinancialDiscountAmount!: number;
    AmountWithFinancialDiscount!: number;
    NumberOfCopies!: number;
    CommitmentsBalanceDue!: number;
    AmountVatExcluded!: number;
    CostPrice!: number;
    DiscountRate!: number;
    DiscountAmount!: number;
    AmountVatExcludedWithDiscount!: number;
    DetailTaxAmount0_BaseAmount!: number;
    DetailTaxAmount0_TaxAmount!: number;
    DetailTaxAmount1_BaseAmount!: number;
    DetailTaxAmount1_TaxAmount!: number;
    DetailTaxAmount2_BaseAmount!: number;
    DetailTaxAmount2_TaxAmount!: number;
    CurrencyConversionRate!: number;
    CurrencyTotalDueAmount!: number;
    CommitmentsCurrencyBalanceDue!: number;
    CurrencyAmountVatIncluded!: number;
    CurrencyApplicationType!: number;
    CurrencyAmountVatExcluded!: number;
    CurrencyAmountVatExcludedWithDiscountAndShipping!: number;
    CurrencyAmountWithFinancialDiscount!: number;
    CurrencyShippingAmountVatExcluded!: number;
    CurrencyAmountVatExcludedWithDiscount!: number;
    CurrencyAmountVatExcludedWithDiscountAndShippingWithoutEcotax!: number;
    CurrencyEcotaxAmountVatIncluded!: number;
    CurrencyFinancialDiscountAmount!: number;
    CurrencyVatAmountWithoutEcotax!: number;
    CurrencyEcotaxVatAmount!: number;
    CurrencyEcotaxAmountVatExcluded!: number;
    CurrencyVatAmount!: number;
    CurrencyDiscountAmount!: number;
    DocumentType!: number;
    InterestAmountVatExcluded!: number;
    InterestRate!: number;
    HumanServiceTotalAmount!: number;
    HumanServiceAmountSettledByOther!: number;
    HumanServiceAmountSettledByCESU!: number;
    HumanServiceAmountSettledByCESUP!: number;
    HumanServiceDeductibleAmount!: number;
    GrossInterestBase!: number;
    GrossInterestRate!: number;
    GrossInterestAmount!: number;
    Printed: boolean = false;
    SubjectToRE: boolean = false;
    REAmount!: number;
    TotalNetWeight!: number;
    CorrectionType!: number;
    IRPFAmount!: number;
    IRPFRate!: number;
    PriceWithTaxBased: boolean = false;
    CustomerId!: string;
    CustomerName!: string;
    Revision!: string;
    xx_Location: boolean = false;
    xx_Nouveau_Client: boolean = false;
    xx_Separ1: boolean = false;
    xx_Separ2: boolean = false;
  
    //* --------------------------------- Les champs avec des IDs
    ShippingVatId!: string;
    ReportId!: string;
    TerritorialityId!: string;
    VatId!: string;
    InvoicingChargesVatId!: string;
    InvoicingAddressId!: string;
    InvoicingContactId!: string;
    DeliveryAddressId!: string;
    DeliveryContactId!: string;
    AssociatedInvoiceId!: string;
    AssociatedDeliveryOrderId!: string;
    AssociatedOrderId!: string;
    StorehouseId!: string;
    TransferedDocumentId!: string;
    sysModuleId!: string;
    sysDatabaseId!: string;
    sysRecordVersionId!: string;
    ThirdBankAccountId!: string;
    DetailTaxAmount0_VatId!: string;
    DetailTaxAmount1_VatId!: string;
    DetailTaxAmount2_VatId!: string;
    DetailTaxAmount3_VatId!: string;
    DetailTaxAmount4_VatId!: string;
    DetailTaxAmount5_VatId!: string;
    CustomerHeadOfficeAddressId!: string;
    AppliedPriceListLineId!: string;
    Hash_Hash_ChainedId!: string;
    DocumentOptionsId!: string;

  }
  