export interface Event {
    AbsenceRange: null | string;
    AccountingYearId: null | string;
    AchievedDuration_Duration: string;
    AchievedDuration_DurationInHours: string;
    AchievedDuration_EditedDuration: string;
    AchievedDuration_UnitId: string;
    AddressId: null | string;
    Address_Address1: null | string;
    Address_Address2: null | string;
    Address_Address3: null | string;
    Address_Address4: null | string;
    Address_City: null | string;
    Address_CityINSEE: null | string;
    Address_Civility: null | string;
    Address_CodeINSEE: null | string;
    Address_CountryIsoCode: null | string;
    Address_Description: null | string;
    Address_Latitude: null | string | number;
    Address_Longitude: null | string | number;
    Address_Npai: boolean;
    Address_State: null | string;
    Address_ThirdName: null | string;
    Address_WebSite: null | string;
    Address_ZipCode: null | string;
    Caption: string;
    ColleagueId: string;
    CompetenceId: null | string;
    ConflictImageIndicator: null | string;
    ConflictIndicator: number;
    ConflictTypes: number;
    ConflictTypesImage: null | string;
    ConstructionSiteId: null | string;
    ContactId: null | string;
    Contact_AllowUsePersonnalDatas: boolean;
    Contact_CellPhone: null | string;
    Contact_Civility: null | string;
    Contact_Department: null | string;
    Contact_Email: null | string;
    Contact_ExternalId_GoogleId: null | string;
    Contact_ExternalId_OutlookId: null | string;
    Contact_Fax: null | string;
    Contact_FirstName: null | string;
    Contact_Function: null | string;
    Contact_Name: null | string;
    Contact_NaturalPerson: boolean;
    Contact_OptIn: boolean;
    Contact_Phone: null | string;
    CostAmount: string;
    CreatedByExecutionQuote: boolean;
    CreatorColleagueId: null | string;
    CustomerId: null | string;
    DateChangeRemindEnabled: boolean;
    DealId: null | string;
    DisplayType: number;
    DocumentType: number;
    EndDateTime: string;
    EquipmentId: null | string;
    EquipmentTypeId: null | string;
    EventState: number;
    EventType: null | string;
    ExceptionColleagueIds: null | string[];
    ExceptionColleagueSelectionType: number;
    ExceptionCompetenceIds: null | string[];
    ExceptionDaySchedule0_Active: boolean;
    ExceptionDaySchedule0_Customize: boolean;
    ExceptionDaySchedule0_Duration: number;
    ExceptionDaySchedule0_EndTime: string;
    ExceptionDaySchedule0_LunchEndTime: null | string;
    ExceptionDaySchedule0_LunchStartTime: null | string;
    ExceptionDaySchedule0_StartTime: string;
    ExceptionDaySchedule1_Active: boolean;
    ExceptionDaySchedule1_Customize: boolean;
    ExceptionDaySchedule1_Duration: number;
    ExceptionDaySchedule1_EndTime: string;
    ExceptionDaySchedule1_LunchEndTime: null | string;
    ExceptionDaySchedule1_LunchStartTime: null | string;
    ExceptionDaySchedule1_StartTime: string;
    ExceptionDaySchedule2_Active: boolean;
    ExceptionDaySchedule2_Customize: boolean;
    ExceptionDaySchedule2_Duration: number;
    ExceptionDaySchedule2_EndTime: string;
    ExceptionDaySchedule2_LunchEndTime: null | string;
    ExceptionDaySchedule2_LunchStartTime: null | string;
    ExceptionDaySchedule2_StartTime: string;
    ExceptionDaySchedule3_Active: boolean;
    ExceptionDaySchedule3_Customize: boolean;
    ExceptionDaySchedule3_Duration: number;
    ExceptionDaySchedule3_EndTime: string;
    ExceptionDaySchedule3_LunchEndTime: null | string;
    ExceptionDaySchedule3_LunchStartTime: null | string;
    ExceptionDaySchedule3_StartTime: string;
    ExceptionDaySchedule4_Active: boolean;
    ExceptionDaySchedule4_Customize: boolean;
    ExceptionDaySchedule4_Duration: number;
    ExceptionDaySchedule4_EndTime: string;
    ExceptionDaySchedule4_LunchEndTime: null | string;
    ExceptionDaySchedule4_LunchStartTime: null | string;
    ExceptionDaySchedule4_StartTime: string;
    ExceptionDaySchedule5_Active: boolean;
    ExceptionDaySchedule5_Customize: boolean;
    ExceptionDaySchedule5_Duration: number;
    ExceptionDaySchedule5_EndTime: string;
    ExceptionDaySchedule5_LunchEndTime: null | string;
    ExceptionDaySchedule5_LunchStartTime: null | string;
    ExceptionDaySchedule5_StartTime: string;
    ExceptionDaySchedule6_Active: boolean;
    ExceptionDaySchedule6_Customize: boolean;
    ExceptionDaySchedule6_Duration: number;
    ExceptionDaySchedule6_EndTime: string;
    ExceptionDaySchedule6_LunchEndTime: null | string;
    ExceptionDaySchedule6_LunchStartTime: null | string;
    ExceptionDaySchedule6_StartTime: string;
    ExceptionWorked: boolean;
    ExpectedDuration_Duration: string;
    ExpectedDuration_DurationInHours: string;
    ExpectedDuration_EditedDuration: string;
    ExpectedDuration_UnitId: string;
    GlobalPercentComplete: number;
    HourlyCostPrice: string;
    Id: string;
    IncludeInRealizedCost: number;
    InvoiceColleagueId: null | string;
    InvoiceCustomerId: string;
    InvoiceEquipments: boolean;
    InvoiceId: null | string;
    InvoiceInterveners: boolean;
    InvoiceLineId: null | string;
    IsScheduleException: boolean;
    ItemId: null | string;
    LabourOverDuration_Duration: string;
    LabourOverDuration_DurationInHours: string;
    LabourOverDuration_EditedDuration: null | string;
    LabourOverDuration_UnitId: null | string;
    LabourPercentComplete: number;
    LabourRemainingDuration_Duration: string;
    LabourRemainingDuration_DurationInHours: string;
    LabourRemainingDuration_EditedDuration: string;
    LabourRemainingDuration_UnitId: string;
    LabourScheduledDuration_Duration: string;
    LabourScheduledDuration_DurationInHours: string;
    LabourScheduledDuration_EditedDuration: null | string;
    LabourScheduledDuration_UnitId: null | string;
    LabourUpdatedExpectedDuration_Duration: string;
    LabourUpdatedExpectedDuration_DurationInHours: string;
    LabourUpdatedExpectedDuration_EditedDuration: null | string;
    LabourUpdatedExpectedDuration_UnitId: null | string;
    LineOrder: number;
    LineType: number;
    Maintenance_ContractHoursNumberDecremented: string;
    Maintenance_ContractId: null | string;
    Maintenance_CustomerProductId: null | string;
    Maintenance_DecreaseContractCounterForNextEvent: boolean;
    Maintenance_IncidentId: null | string;
    Maintenance_IncludeInContractPredictedCost: number;
    Maintenance_IncludeInIncidentPredictedCost: number;
    Maintenance_InterventionDescription: null | string;
    Maintenance_InterventionDescriptionClear: null | string;
    Maintenance_InterventionReport: null | string;
    Maintenance_InterventionReportClear: null | string;
    Maintenance_InvoiceTravelExpenseOnLastIntervention: number;
    Maintenance_NextEventDate: null | string;
    Maintenance_NextEventToForesee: boolean;
    Maintenance_NextMaintenanceEventId: null | string;
    Maintenance_Reference: null | string;
    Maintenance_ScheduleEventTemplateId: null | string;
    Maintenance_SendConfirmationMail: boolean;
    Maintenance_TravelDuration: string;
    Maintenance_TravelExpenseId: null | string;
    Maintenance_TravelExpenseInvoiceId: null | string;
    MustBeCalculated: boolean;
    NetAmountVatExcluded: string;
    NextReminder: null | string;
    Notes: string;
    NotesClear: string;
    OccupancyRate: number;
    ParentEventId: string;
    PayrollExchangeGroupId: null | string;
    PayrollVariableDuration0: string;
    PayrollVariableDuration1: string;
    PayrollVariableDuration2: string;
    PayrollVariableDuration3: string;
    PayrollVariableDuration4: string;
    PayrollVariableDuration5: string;
    PayrollVariableDuration6: string;
    PayrollVariableDuration7: string;
    PayrollVariableDuration8: string;
    PayrollVariableDuration9: string;
    PayrollVariableDuration10: string;
    PayrollVariableDuration11: string;
    PayrollVariableDuration12: string;
    PayrollVariableDuration13: string;
    PayrollVariableDuration14: string;
    PayrollVariableDuration15: string;
    PayrollVariableDuration16: string;
    PayrollVariableDuration17: string;
    PayrollVariableDuration18: string;
    PayrollVariableDuration19: string;
    PayrollVariableDuration20: string;
    PayrollVariableDuration21: string;
    PayrollVariableDuration22: string;
    PayrollVariableDuration23: string;
    PayrollVariableDuration24: string;
    PayrollVariableDuration25: string;
    PayrollVariableDuration26: string;
    PayrollVariableDuration27: string;
    PayrollVariableDuration28: string;
    PayrollVariableDuration29: string;
    PayrollVariableDuration30: string;
    PayrollVariableDuration31: string;
    PayrollVariableDuration32: string;
    PayrollVariableDuration33: string;
    PayrollVariableDuration34: string;
    PayrollVariableDuration35: string;
    PayrollVariableDuration36: string;
    PayrollVariableDuration37: string;
    PayrollVariableDuration38: string;
    PayrollVariableDuration39: string;
    PayrollVariableDuration40: string;
    PayrollVariableDuration41: string;
    PayrollVariableDuration42: string;
    PayrollVariableDuration43: string;
    PayrollVariableDuration44: string;
    PayrollVariableDuration45: string;
    PayrollVariableDuration46: string;
    PayrollVariableDuration47: string;
    PayrollVariableDuration48: string;
    PayrollVariableDuration49: string;
    PlannedHours: string;
    PredictedCostAmount: string;
    ProgressUpdateLastDate: string;
    PurchaseDocumentId: null | string;
    Quantity: string;
    Reminder: number;
    ReminderEnabled: boolean;
    ReminderType: number;
    SaleDocumentId: null | string;
    SaleDocumentLineid: null | string;
    SalePriceVatExcluded: string;
    ScheduleEventNumber: string;
    ScheduleShowTimeLine: boolean;
    StartDateTime: string;
    StockDocumentId: null | string;
    SubContractorId: null | string;
    SupplierId: null | string;
    ToInvoice: boolean;
    UpdatedWorkingDuration_Duration: string;
    UpdatedWorkingDuration_DurationInHours: string;
    UpdatedWorkingDuration_EditedDuration: null | string;
    UpdatedWorkingDuration_UnitId: null | string;
    WorkedHours: string;
    WorkingDuration_Duration: string;
    WorkingDuration_DurationInHours: string;
    WorkingDuration_EditedDuration: null | string;
    WorkingDuration_UnitId: null | string;
    sysCreatedDate: string;
    sysCreatedUser: string;
    sysEditCounter: number;
    sysModifiedDate: string;
    sysModifiedUser: string;
    xx_Activite: null | string;
    xx_Duree_Pevue: null | string;
    xx_Duree_Trajet: null | string;
    xx_Fournisseur: null | string;
    xx_Gestion_Projet_Posit: null | string;
    xx_Logiciel: string;
    xx_Projet: boolean;
    xx_Services: string;
    xx_Theme: string;
    xx_Theme_Commercial: null | string;
    xx_Total_Temps_Realise: string;
    xx_Total_Temps_Realise_Client: null | string;
    xx_Total_Temps_Realise_Formation: null | string;
    xx_Total_Temps_Realise_Interne: null | string;
    xx_Total_Temps_Realise_Maquettage: null | string;
    xx_Total_Temps_Realise_Relationnel: null | string;
    xx_Total_Temps_Realise_Trajet: null | string;
    xx_Type_Tache: null | string;
    xx_URGENT: boolean;
  }

  export interface EventType {
    Id: string;
    Caption: string;
    Color: number;
    sysEditCounter: number;
    sysCreatedDate: string;
    sysCreatedUser: string;
    sysModifiedDate: string;
    sysModifiedUser: string;
    NotesClear: string | null;
    Notes: string | null;
    DisplayType: number;
    LocalizableCaption_2: string | null;
    LocalizableCaption_3: string | null;
    LocalizableCaption_4: string | null;
    LocalizableCaption_5: string | null;
  }