export default interface StockDocument {
  AccountingExchangeGroupId: null | string;
  ConstructionSiteId: null | string;
  CreatedFromConstructionSiteConsumptions: string;
  DealId: null | string;
  DefaultActivateInventoryQuantityFormula: string;
  DispatchedByStorehouse: string;
  DocumentDate: string;
  DocumentNumber: string;
  DocumentStage: number;
  DocumentType: number;
  ExecutionQuoteId: null | string;
  GlobalDocumentOrder: number;
  GroupingType: null | string;
  Hash_ChainedId: null | string;
  Hash_Hash: null | string;
  Id: string;
  IncidentId: null | string;
  IncludeSoldOutTrackingNumbers: string;
  InvoiceId: null | string;
  IsExchangeDocument: string;
  ItemValueType: number;
  MaintenanceContractId: null | string;
  ModifiedSinceRecovery: string;
  MustBeTransferedToAccounting: string;
  MustGetQuantities: string;
  Notes: null | string;
  NotesClear: null | string;
  NumberPrefix: string;
  NumberSuffix: string;
  OriginDocumentId: null | string;
  OriginDocumentType: null | string;
  PreparationState: number;
  ProcessDate: null | string;
  ProgressStateDocumentId: null | string;
  RecoveredFrom: null | string;
  Reference: null | string;
  RemoveOutOfDateBestBeforeStock: string;
  RemoveOutOfDateUseByStock: string;
  ScheduleEventId: null | string;
  SerialId: string;
  SortingType: null | string;
  StorehouseId: string;
  SysCreatedDate: string;
  SysCreatedUser: string;
  SysDatabaseId: null | string;
  SysEditCounter: number;
  SysModifiedDate: string;
  SysModifiedUser: string;
  SysModuleId: null | string;
  SysRecordVersion: number;
  SysRecordVersionId: string;
  TargetStorehouseId: null | string;
  TotalVolume: string;
  TotalWeight: string;
  TransferedDocumentId: null | string;
  TransitDuration: null | string;
  TransitEndDate: null | string;
  TransitStorehouseId: null | string;
  UseAdjustedLimitDate: string;
  UseMaxPrecisionForPump: string;
  ValidateState: null | string;
  ValidationDate: null | string;
  ValidationGlobalDocumentOrder: null | string;
}


export default interface StockDocumentLine {
  BillOfQuantitiesProgram_IsActive: string;
  FixedQuantity: string;
  Booked: string;
  StockBookingAllowed: string;
  ToInvoice: string;
  TargetLocation_MultiLocationMode: number;
  TransitLocation_MultiLocationMode: number;
  PhaseLevel: number;
  UpdateComponentsStockInFabrication: string;
  Id: string;
  DocumentId: string;
  LineType: number;
  LineOrder: number;
  IsReferencedItem: string;
  Quantity: string;
  RealQuantity: string;
  ManageStock: string;
  NomenclatureLevel: number;
  IsPrintable: number;
  QuantityDecimalNumber: number;
  PricesDecimalNumber: number;
  IsManagedByCountermark: string;
  IsCountermarkInitiated: string;
  Volume: string;
  TotalVolume: string;
  HasTrackingDispatch: string;
  Weight: string;
  TotalWeight: string;
  ItemValue: string;
  TotalValue: string;
  CurrentStock: string;
  NewTotalValue: string;
  AccountingNewTotalValue: string;
  ExistingTrackingNumber: string;
  TrackingMasterLine: string;
  PreviousTotalValue: string;
  Location_MultiLocationMode: number;
  MustProcessOriginQuantity: string;
  DealId: string | null;
  TransitLocation_LocationId: string | null;
  Gap: string;
  JustificationQuantity1: string;
  JustificationQuantity2: string;
  JustificationQuantity3: string;
  JustificationQuantity4: string;
  JustificationQuantity5: string;
  TargetStorehouseId: string | null;
  ReceivedQuantity: string | null;
  TargetStockMovementId: string | null;
  StockChargeAmount: string | null;
  GapStockMovementId: string | null;
  OriginLineId: string | null;
  RemainingQuantity: string | null;
  TargetQuantity: string | null;
  TransitInputStockMovementId: string | null;
  TransitOutputStockMovementId: string | null;
  LocationCaption: string | null;
  UnitCaption: string | null;
  Commentary: string | null;
  NewPump: string;
  CurrentPump: string;
  WeightUnitId: string | null;
  LimitDate: string | null;
  VolumeUnitId: string | null;
  TrackingNumber: string | null;
  UnitId: string | null;
  StorehouseId: string;
  StockMovementId: number;
  Description: string;
  DescriptionClear: string;
  ItemId: string;
  ParentLineId: string | null;
  TopParentLineId: string | null;
  SysCreatedDate: string;
  SysCreatedUser: string;
  SysModifiedDate: string;
  SysModifiedUser: string;
  Location_LocationId: string | null;
  TargetLocation_LocationId: string | null;
  RangeItemId: string | null;
  MaintenanceContractId: string | null;
  GuaranteeTypeId: string | null;
  IncidentId: string | null;
  InvoiceLineId: string | null;
  CustomerProductId: string | null;
  BillOfQuantitiesProgram_Program: string | null;
  TechnicalDescription: string | null;
  TechnicalDescriptionClear: string | null;
  ExecutionQuoteLineId: string | null;
  ProgressDocumentLineId: string | null;
}


export interface Storehouse {
  Address_Address1: string;
  Address_Address2: string;
  Address_Address3: string | null;
  Address_Address4: string | null;
  Address_City: string;
  Address_CountryIsoCode: string;
  Address_Latitude: number | null;
  Address_Longitude: number | null;
  Address_State: string;
  Address_ZipCode: string;
  Asleep: string;
  Caption: string;
  Contact_CellPhone: string | null;
  Contact_Civility: string | null;
  Contact_Email: string | null;
  Contact_Fax: string | null;
  Contact_FirstName: string | null;
  Contact_Name: string | null;
  Contact_Phone: string | null;
  Id: string;
  LastInventoryDate: string;
  Main: string;
  MultiLocationDefaultMode: number;
  MultiLocationEnabled: string;
  Notes: string | null;
  NotesClear: string | null;
  SysCreatedDate: string;
  SysCreatedUser: string;
  SysEditCounter: number;
  SysModifiedDate: string;
  SysModifiedUser: string;
  Type: number;
}


export default interface StockDocumentLineWithPrice extends StockDocumentLine {
  SalePriceVatIncluded: string | number | null;
}