export default interface Supplier {
    AssortDeliveryByOrder: string;
    DisallowOrderAssort: string;
    DisallowDeliveryAssort: string;
    VatMode: number;
    ExtendedCurrentAmount: string;
    ThresholdBeforeExceedAmount: string;
    Id: string;
    Name: string;
    UseInvoicingAddressAsDeliveryAddress: string;
    UseInvoicingContactAsDeliveryContact: string;
    MainDeliveryAddress_NPAI: string;
    MainInvoicingAddress_NPAI: string;
    MainDeliveryContact_NaturalPerson: string;
    MainDeliveryContact_OptIn: string;
    MainInvoicingContact_NaturalPerson: string;
    MainInvoicingContact_OptIn: string;
    NaturalPerson: string;
    TerritorialityId: string;
    DiscountRate: string;
    SecondDiscountRate: string;
    AllowedAmount: string;
    CurrentAmount: string;
    InitialAmount: string;
    ExceedAmount: string;
    FinancialDiscountType: number;
    FinancialDiscountRate: string;
    FinancialDiscountPaymentDelay: number;
    ActiveState: number;
    MustRetrieveCommitmentsFromAccounting: string;
    Irpfrate: string;
    UniqueId: string;
    ThirdLanguage: string;
    InvoicingChargesAmount: string;
    IsSelfBilling: string;
    PostagePaidThreshold: string;
    Accounts_AuxiliaryAccount: string | null;
    SchedulerColor: string | null;
    SelfBillingId: string | null;
    SelfBillingInvoiceObligatoryMentions: string | null;
    SelfBillingInvoiceObligatoryMentionsClear: string | null;
    InvoicingChargesVatId: string;
    LastInvoicingDate: string;
    DocumentPrintMention: string | null;
    SysRecordVersion: number;
    SysRecordVersionId: string;
    SysEditCounter: number;
    DocumentSerialId: string | null;
    IdentificationType: string | null;
    AnalyticAccounting_GridId: string | null;
    CurrencyId: string | null;
    Group1: string | null;
    Group2: string | null;
    ColleagueId: string | null;
    Accounts_Account: string;
    FirstInvoicingDate: string;
    SettlementModeId: string | null;
    PaymentDate: string | null;
    PricelistCategoryId: string | null;
    Siren: string | null;
    Naf: string | null;
    FamilyId: string | null;
    SubfamilyId: string | null;
    IntracommunityVatNumber: string | null;
    MainInvoicingContact_ExternalId_GoogleId: string | null;
    MainInvoicingContact_ExternalId_OutlookId: string | null;
    MainDeliveryContact_ExternalId_GoogleId: string | null;
    MainDeliveryContact_ExternalId_OutlookId: string | null;
    MainInvoicingContact_Civility: string | null;
    MainInvoicingContact_Name: string;
    MainInvoicingContact_FirstName: string | null;
    MainInvoicingContact_Phone: string | null;
    MainInvoicingContact_CellPhone: string | null;
    MainInvoicingContact_Fax: string | null;
    MainInvoicingContact_Email: string | null;
    MainInvoicingContact_Function: string | null;
    MainInvoicingContact_Department: string | null;
    MainInvoicingAddress_Website: string | null;
    MainInvoicingAddress_Longitude: string | null;
    MainInvoicingAddress_Latitude: string | null;
    MainDeliveryContact_Civility: string | null;
    MainDeliveryContact_Name: string;
    MainDeliveryContact_FirstName: string | null;
    MainDeliveryContact_Phone: string | null;
    MainDeliveryContact_CellPhone: string | null;
    MainDeliveryContact_Fax: string | null;
    MainDeliveryContact_Email: string | null;
    MainDeliveryContact_Function: string | null;
    MainDeliveryContact_Department: string | null;
    MainDeliveryAddress_Website: string | null;
    MainDeliveryAddress_Longitude: string | null;
    MainDeliveryAddress_Latitude: string | null;
    MainInvoicingAddress_Address1: string;
    MainInvoicingAddress_Address2: string | null;
    MainInvoicingAddress_Address3: string | null;
    MainInvoicingAddress_Address4: string | null;
    MainInvoicingAddress_ZipCode: string;
    MainInvoicingAddress_City: string;
    MainInvoicingAddress_State: string;
    MainInvoicingAddress_CountryIsoCode: string;
    MainInvoicingAddress_Description: string;
    MainInvoicingAddress_Civility: string | null;
    MainInvoicingAddress_ThirdName: string;
    MainDeliveryAddress_Address1: string;
    MainDeliveryAddress_Address2: string | null;
    MainDeliveryAddress_Address3: string | null;
    MainDeliveryAddress_Address4: string | null;
    MainDeliveryAddress_ZipCode: string;
    MainDeliveryAddress_City: string;
    MainDeliveryAddress_State: string;
    MainDeliveryAddress_CountryIsoCode: string;
    MainDeliveryAddress_Description: string;
    MainDeliveryAddress_Civility: string | null;
    MainDeliveryAddress_ThirdName: string;
    Civility: string | null;
    SysCreatedDate: string;
    SysCreatedUser: string;
    SysModifiedDate: string;
    SysModifiedUser: string;
    NotesClear: string | null;
    Notes: string | null;
    Accounts_BillOfExchangeAccountingAccount: string;
    TaxIds0: string | null;
    TaxIds1: string | null;
    TaxIds2: string | null;
    ShippingId: string | null;
    PaymentThirdId: string | null;
    InvoicingThirdId: string | null;
    SupplierType: number;
    CompetenceId: string | null;
    IsEcoTaxFurnitureBasedOnAmountVatIncluded: string;
    MainDeliveryContact_AllowUsePersonalDatas: string | null;
    MainInvoicingContact_AllowUsePersonalDatas: string | null;
    AllowUsePersonalDatas: string;
    Nic: string | null;
}
